security:
    # Hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Route de connexion (login)
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Routes API protégées par JWT
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            lazy: true
            jwt: ~

    access_control:
        # --- ROUTES PUBLIQUES ---
        - { path: ^/api/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/books$, roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: ^/api/books/\d+$, roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: ^/api/password/reset-request, roles: PUBLIC_ACCESS }
        - { path: ^/api/password/reset-confirm, roles: PUBLIC_ACCESS }

        # --- ADMIN ---
        - { path: ^/api/users$, roles: ROLE_ADMIN }
        - { path: '^/api/users/[0-9a-f-]{36}$', roles: IS_AUTHENTICATED_FULLY }

        # --- TOUT LE RESTE REQUIERT AUTHENTIFICATION ---
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
