FROM php:8.3-fpm-alpine

# Dépendances système + outils de build pour PECL
RUN apk add --no-cache \
    bash git unzip curl \
    icu-dev libzip-dev \
    openssl-dev pkgconf \
    $PHPIZE_DEPS

# Extensions PHP nécessaires à Symfony
RUN docker-php-ext-install pdo_mysql zip intl opcache

# MongoDB extension via PECL (non-interactive), puis activation
RUN yes '' | pecl install mongodb \
    && docker-php-ext-enable mongodb

# (Optionnel mais très utile pour valider que c'est OK)
RUN php -m | grep -i mongodb

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Dépendances PHP (après que mongodb soit activé)
COPY composer.json composer.lock ./
RUN composer install --no-interaction --no-scripts --optimize-autoloader

# Code source
COPY . .

RUN mkdir -p var/cache var/log \
    && chown -R www-data:www-data var

EXPOSE 8000
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
